### PR TITLE
Remove PartnerId and ContactEmail in ApiClient

### PR DESCRIPTION
**Pull request by Misaka-L**
Remove PartnerId and ContactEmail in ApiClient because it's unnecessary.

### CODE REVIEW

**Comment by itssimple** [comment]
The reason I'm having PartnerId and ContactEmail, is so that it's easier for CurseForge to contact the person behind the API client, in case it starts abusing the API, or using it in a way that is not "good".

**Comment by Misaka-L** [comment]
> The reason I'm having PartnerId and ContactEmail, is so that it's easier for CurseForge to contact the person behind the API client, in case it starts abusing the API, or using it in a way that is not "good".

I know now. But can we add a constructor that doesn't have these args?

**Comment by itssimple** [comment]
> > The reason I'm having PartnerId and ContactEmail, is so that it's easier for CurseForge to contact the person behind the API client, in case it starts abusing the API, or using it in a way that is not "good".
> 
> I know now. But can we add a constructor that doesn't have these args?

Yeah, I'll publish a version that doesn't require `contactEmail`, so there'll be 3 constructors.

**Comment by itssimple** [comment]
I added the new constructor and updated the API methods that had been updated. :) Closing this!

**Pull request closed without merging**
